name: Bruno API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli

      - name: Show files
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type f -name "*.bru" -print

      - name: Bruno version
        run: bru --version


      # Spusti collection (root priečinok alebo konkrétny folder)
      - name: Run Bruno (CI env)
        run: |
          bru run ./pet \
            --env env-qa \
            --reporter-html bruno-results.html \
            --reporter-junit bruno-results.xml

      - name: Upload reports
        if: ${{ always() }} 
        uses: actions/upload-artifact@v4
        with:
          name: bruno-reports
          path: |
            bruno-results.html
            bruno-results.xml
